---
title: "panelTest"
output: html_document
---

타이틀 영역
-----------
> title: "panelTest"
  output: html_document

현재는 html_document로 작성합니다.

flexdashboard를 사용할 때 타이틀 영역
-------------------------------------
> title: "panelTest"
output: 
flexdashboard::flex_dashboard:
storyboard: true
social: menu
source: embed

R Script 전체
-------------
```{r panel}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(flexdashboard)
library(shinydashboard)
library(leaflet)
# View(df)

ui <- fluidPage(
  # headerPanel(
  #   flowLayout(
  #     "CCTV, TASHU 위치"
  #   )
  # ),
  
  mainPanel(
    leafletOutput("theMap", height = 1000)
  )
  # mainPanel(
  # tabsetPanel(
  #   tabPanel("Plot", plotOutput("plot")),
  #   tabPanel("Summary", verbatimTextOutput("summary")),
  #   tabPanel("Table", tableOutput("table"))
  # )
  
  #sidebarPanel(
  #navlistPanel(
  #  tabPanel("모두 조회",NULL),
  #  tabPanel("CCTV 조회",NULL),
  #  tabPanel("TASHU 조회",NULL)
  #)
  #)
)


# server
####################################
# 변수선언
resPath = "resources/"
cctvDataNm = "cctv_clean.csv"
tashuDataNm = "tashu_station.csv"

# 기본타입색 1:CCTV 2:TASHU
rootTypeColors <- c("1"="navy", "2"="red")

# CCTV 위치정보조회
getLocationCCTV <- function(){
  path <- paste0(resPath,cctvDataNm)
  read.csv(path,header = T)
}

# TASHU 위치정보조회
getLocationTASHU <- function(){
  path <- paste0(resPath,tashuDataNm)
  read.csv(path,header = T)
}

server <- function(input, output){
  points <- eventReactive(input$recalc, {
    cbind(rnorm(40) * 2 + 13, rnorm(40) + 48)
  }, ignoreNULL = FALSE)
  
  cctv <- getLocationCCTV()
  tashu <- getLocationTASHU()
  
  #df = data.frame(Lat = 1:10, Long = rnorm(10))
  output$theMap <- renderLeaflet({
    leaflet(options = leafletOptions(
        maxZoom=14, minZoom=9, attributionControl = T
      )) %>%
      addProviderTiles(providers$OpenStreetMap.Mapnik,
        options = providerTileOptions(noWrap = TRUE)
      ) %>%
      addTiles(group = "OSM (default)", 
                options = providerTileOptions(noWrap = TRUE)) %>%
      addProviderTiles(providers$Stamen.Toner, group = "Toner", 
                        options = providerTileOptions(noWrap = TRUE)) %>%
      addProviderTiles(providers$Stamen.TonerLite, group = "Toner Lite", 
                        options = providerTileOptions(noWrap = TRUE)) %>%
      addCircles(
        data=cctv, radius=20, lng=~LNG, lat=~LAT, color='red',
        fillOpacity=0.5, group="CCTV"
      ) %>%
      addCircles(
        data=tashu, radius=20, lng=~LNG, lat=~LAT, color = 'navy',
        fillOpacity=0.5, group="TASHU"
      ) %>%
      addLayersControl(
        baseGroups = c("OSM (default)", "Toner", "Mapnik", "Toner Lite"),
        overlayGroups = c("CCTV", "TASHU"),
        options = layersControlOptions(collapsed = FALSE)
      )
  })
}
shinyApp(ui=ui, server=server)
```


## setup
```{r setup}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(flexdashboard)
library(leaflet)
```

## UI
```{r ui}
ui <- pageWithSidebar(
  headerPanel(
    flowLayout(
      "1","2","3","4"
    )
  ),
  
  mainPanel(
    "main panel",
    leafletOutput("theMap")
  ),
  # mainPanel(
  # tabsetPanel(
  #   tabPanel("Plot", plotOutput("plot")),
  #   tabPanel("Summary", verbatimTextOutput("summary")),
  #   tabPanel("Table", tableOutput("table"))
  # )

  #sidebarPanel(
    navlistPanel(
      tabPanel("a",NULL),
      tabPanel("a",NULL),
      tabPanel("a",NULL)
    )
  #)
)
```


## SERVER
```{r server}
server <- function(input, output){
  points <- eventReactive(input$recalc, {
    cbind(rnorm(40) * 2 + 13, rnorm(40) + 48)
  }, ignoreNULL = FALSE)

  df = data.frame(Lat = 1:10, Long = rnorm(10))
  output$theMap <- renderLeaflet({
    leaflet(options = leafletOptions(
        #maxZoom=12
        # ,attributionControl = T
        # ,zoomControl = F1
      )) %>%
      addProviderTiles(providers$OpenStreetMap.Mapnik,
        options = providerTileOptions(noWrap = TRUE)
      ) %>%
      #addMarkers(data = cbind(127.38, 36.35))
      #addMarkers(lng=127.38, lat=36.35)
      addCircles(radius = 1000, lng=127.38, lat=36.35)
  })
}
```

## R Shiny 실행
```{r shinyApp}
shinyApp(ui=ui, server=server)
```